<template>
  <div>
    <h1 class="mb-6">Allgemeine Geschäftsbedingungen</h1>
    <h2 class="text-lg xl:text-xl mb-4">Begriffsbestimmungen und Anwendungsbereich</h2>
    <p class="mb-4">Diese AGB gelten zwischen der Joswig Solutions UG (haftungsbeschränkt), Schaperstraße 14, 10719 Berlin („traumanwalt.com“) und dem Anwalt bzw. der Anwältin bzw. der Gesellschaft („Kunde”), die/der einen Profileintrag („Profil“) auf einer Internetseite von traumanwalt.com gebucht hat.</p>
    <p class="mb-6">Abweichenden AGB von Kunden wird hiermit ausdrücklich widersprochen. Individualvereinbarungen bedürfen zu ihrer Wirksamkeit einer Bestätigung durch traumanwalt.com in Textform. Individualvereinbarungen zwischen traumanwalt.com und dem Kunden gehen diesen AGB im Bereich der jeweils individuell vereinbarten Vertragsbedingung vor (vgl. § 305 BGB) und werden sodann durch diese AGB ergänzt.</p>
    <h2 class="text-lg xl:text-xl mb-4">Profil</h2>
    <p class="mb-4">Das Profil wird in der Regel spätestens drei Werktage nach Vertragsschluss von traumanwalt.com erstellt und online geschaltet. Stellt der Kunde keine über die Grunddaten hinausgehenden Daten bzw. Materialien zur Verfügung, erstellt traumanwalt.com das Profil aus vorliegenden Daten.</p>
    <p class="mb-4">Der Kunde gestattet traumanwalt.com die Verwendung von Daten, insbesondere Text- und Bildmaterial seiner Website, zur Erstellung des Profils und räumt traumanwalt.com die dafür notwendigen Nutzungsrechte ein. Der Kunde sichert die Aktualität, Richtigkeit und Vollständigkeit der auf seiner Website verwendeten Daten zu.</p>
    <p class="mb-4">Der Kunde erhält Zugang zu einem persönlichen Login-Bereich. Der Kunde hat keinen Anspruch auf Veröffentlichung bestimmter Inhalte oder einer bestimmten Form der Darstellung seines Profils. Insbesondere Hyperlinks, die auf Seiten außerhalb von www.traumanwalt.com verweisen, können von traumanwalt.com entfernt werden.</p>
    <p class="mb-4">traumanwalt.com teilt jedem Profil eine individuelle Internet-Adresse („Shortlink“) in der Form www.traumanwalt.com/[BEZEICHNUNG] zu. Shortlinks können auch ohne Zustimmung des Kunden nachträglich angepasst werden. Der Kunde wird über eine Anpassung des Shortlinks informiert.</p>
    <p class="mb-4">Der Kunde ist verpflichtet, das Profil während der gesamten Vertragslaufzeit regelmäßig auf inhaltliche Vollständigkeit und Richtigkeit hin zu überprüfen und traumanwalt.com Fehler unverzüglich mitzuteilen. Relevante Änderungen (z. B. der Kanzleiadresse, der Rufnummer, des Tätigkeitsgebiets, des Fachanwaltstitels etc.) hat der Kunde unverzüglich traumanwalt.com mitzuteilen.</p>
    <p class="mb-6">traumanwalt.com nimmt keine rechtliche Prüfung des Profils vor. Allein verantwortlich für den Profilinhalt ist der Kunde. Dies gilt auch bei Profilerstellung durch traumanwalt.com. Der Kunde ist verpflichtet, geltende Gesetze und berufsständischen Pflichten, insbesondere § 206 BRAO und § 1 EuRAG, hinsichtlich der Berufsausübung, Niederlassung und Berufsbezeichnung selbstständig zu beachten und zu überwachen. Für Verstöße ist allein der Kunde verantwortlich, eine diesbezügliche Haftung von traumanwalt.com ist ausgeschlossen.</p>
    <h2 class="text-lg xl:text-xl mb-4">Rechtstipps</h2>
    <p class="mb-4">Der Kunde kann im persönlichen Login-Bereich eine begrenzte Zahl Texte oder Videodateien („Rechtstipps“) zur Veröffentlichung vorlegen. Die Veröffentlichung erfolgt mit Freischaltung durch traumanwalt.com und ist auf maximal einen Rechtstipp je aktivem Profil und Geschäftstag von traumanwalt.com beschränkt. Über Zeitpunkt der Freischaltung, Formatierung und Darstellung bestimmt allein traumanwalt.com.</p>
    <p class="mb-4">Veröffentlicht werden nur selbstverfasste Rechtstipps zu juristischen und rechtspolitischen Themen, die im Rahmen der Suchmaschinenoptimierung ein hohes Maß an Einzigartigkeit aufweisen und keine reine Eigenwerbung sind. Redaktionelle Änderungen behält sich traumanwalt.com in Grenzen des Urheberpersönlichkeitsrechts vor. Der Kunde hat keinen Anspruch auf Veröffentlichung bestimmter Rechtstipps.</p>
    <p class="mb-6">Beiträge dürfen keine aktiven Hyperlinks, Computercode o. Ä. enthalten. traumanwalt.com ist nicht für die rechtliche und/oder inhaltliche Prüfung von Beiträgen verantwortlich.</p>
    <h2 class="text-lg xl:text-xl mb-4">Urheber- und Nutzungsrechte</h2>
    <p class="mb-6">Der Kunde sichert zu und garantiert, dass er zur Nutzung der Texte und sonstigen Materialien nach vorstehenden Ziffern, die er zur Profilgestaltung und/oder sonstigen Verwendung (Rechtstipps etc.) an traumanwalt.com übermittelt oder deren Verwendung er traumanwalt.com gestattet, berechtigt ist und keine Rechte Dritter entgegenstehen.</p>
    <h2 class="text-lg xl:text-xl mb-4">Haftung des Kunden und Freistellung</h2>
    <p class="mb-6">Der Kunde stellt traumanwalt.com und dessen Erfüllungsgehilfen von allen Ansprüchen Dritter frei, die diese aufgrund der Verletzung einer der in diesen AGB festgelegten Pflichten des Kunden gegenüber traumanwalt.com und dessen Erfüllungsgehilfen geltend machen. Dies umfasst auch den Ersatz der hieraus resultierenden Schäden, einschließlich der Kosten für eine angemessene Rechtsverteidigung.</p>
    <h2 class="text-lg xl:text-xl mb-4">Gewährleistung und Haftung</h2>
    <p class="mb-6">Mandatsverhältnisse über Rechtsdienstleistungen kommen, auch sofern über traumanwalt.com vermittelt, nur unmittelbar zwischen dem Kunden als Rechtsanwalt und dem Rechtsratsuchenden als Mandanten zustande. Für die anwaltliche Leistung haftet allein der Kunde. Der Kunde stellt traumanwalt.com auch von sämtlichen Ansprüchen Dritter frei, die diese gegen traumanwalt.com wegen Verletzung von Urheber-, Wettbewerbs-, Berufs-, Schadensersatz- oder sonstigen Rechten in Zusammenhang mit dem individuellen Profil oder durch den Kunden bereitgestellte Beiträge geltend machen. Dies umfasst auch die Kosten einer erforderlichen Rechtsverteidigung, die direkt oder indirekt durch die Inanspruchnahme von traumanwalt.com entstehen.</p>
    <h2 class="text-lg xl:text-xl mb-4">Vertragslaufzeit, Kündigung, Preise und Zahlung</h2>
    <p class="mb-4">Die Vertragslaufzeit beträgt 12 Monate. Der Vertrag verlängert sich automatisch jeweils um weitere 12 Monate, sofern er nicht mindestens einen Monat vor Ende der jeweiligen Vertragslaufzeit in Textform gekündigt wird. Das Recht zur außerordentlichen Kündigung bleibt unberührt.</p>
    <p class="mb-4">Die Leistungserbringung durch traumanwalt.com erfolgt während dieser Vertragslaufzeit jeweils monatlich anteilig.</p>
    <p class="mb-4">Es gelten die unter www.traumanwalt.com/mitgliedschaft veröffentlichten Preise. Alle Preise in den Unterlagen und Angeboten von traumanwalt.com verstehen sich als Nettopreise zuzüglich der bei Leistungserbringung jeweils geltenden Mehrwertsteuer. traumanwalt.com behält sich angemessene Preisanpassungen aufgrund veränderter Produktions-/Vertriebskosten oder Leistungserweiterungen vor. Preisanpassungen werden mitgeteilt. Sie wirken sich nicht auf die laufende Vertragslaufzeit aus, berechtigen jedoch zur außerordentlichen Kündigung des Vertrages, wenn eine ordentliche Kündigung zum aktuellen Laufzeitende nicht mehr erfolgen könnte.</p>
    <p class="mb-6">Das Recht zur Rechnungsstellung vor Leistungserbringung bleibt traumanwalt.com vorbehalten. Der Rechnungsbetrag für die gesamte Vertragslaufzeit wird in der Regel zu Beginn der jeweiligen Vertragslaufzeit mit Rechnungsstellung fällig. Im Falle des Zahlungsverzugs des Kunden steht traumanwalt.com nach zweimaliger erfolgloser Zahlungsaufforderung ein außerordentliches Kündigungsrecht zu.</p>
    <h2 class="text-lg xl:text-xl mb-4">Schlussbestimmungen</h2>
    <p class="mb-4">traumanwalt.com behält sich Änderungen der AGB vor. Geänderte AGB werden dem Kunden 6 Wochen vor Inkrafttreten an dessen hinterlegte E-Mail-Adresse mitgeteilt. Widerspricht der Kunde nicht innerhalb von 6 Wochen nach der Mitteilung, gelten die geänderten AGB als genehmigt und werden damit zum Bestandteil des Vertrages. traumanwalt.com macht den Kunden auf diesen Umstand besonders aufmerksam und behält sich vor, bei Widerspruch des Kunden das Vertragsverhältnis unter Wahrung dessen berechtigter Interessen zu kündigen oder unter Geltung der alten AGB fortzuführen. Ein Anspruch des Kunden gegenüber traumanwalt.com hinsichtlich eines bestimmten Vorgehens in diesem Fall besteht nicht.</p>
    <p class="mb-6">Änderungen, Ergänzungen und Aufhebung des Vertrages bedürfen der Schriftform, was auch für die Abbedingung des Schriftformerfordernisses gilt. Soweit einzelne Bestimmungen dieser AGB ganz oder teilweise unwirksam sind, wird die Wirksamkeit des Vertrages sowie der übrigen Bestimmungen hiervon nicht berührt. Anstelle der unwirksamen Bestimmung ist eine Bestimmung zu vereinbaren, die dem Sinn und Zweck der weggefallenen Bestimmung am nächsten kommt. Es gilt deutsches Recht. Die Geltung des Übereinkommens der Vereinten Nationen über den Internationalen Warenkauf sowie die Regelungen zum internationalen Kaufrecht werden ausgeschlossen. Erfüllungsort und Gerichtsstand für Streitigkeiten diese Vereinbarung betreffend ist Berlin. Hinsichtlich des Gerichtsstands gilt dies nur, sofern das Gesetz nicht zwingend etwas anderes vorschreibt.</p>
    <p>Joswig Solutions UG (haftungsbeschränkt)</p>
    <p>Berlin, September 2023</p>
  </div>
</template>

<script>
export default {
  name: 'AgbPage',
  head() {
    return {
      title: 'Allgemeine Geschäftsbedingungen - Traumanwalt'
    }
  }
}
</script>
